#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=CheckEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:00:00
#SBATCH --output=outs/slurm_output_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

source ai4mi/bin/activate

python3.11 -O main.py --dataset SEGTHOR_CLEAN --mode full --epoch 25 --dest ./data/results_baseline --gpu
